### ISSUE TITLE
Can I turn off the `prefer-smart-quotes/prefer` rule?

### ISSUE THREAD

**Issue by ronny1020** [totallymoney/eslint-plugin-prefer-smart-quotes#6]
Hi, I would like to turn off this rule in my test file. And I add this rule to the overrides in `eslintrc` file with `off`. I think it's not working with off. Could this feature be added to this? Thanks.

**Comment by ljbc1994** [comment]
Hi @ronny1020,

I've just tested it using the `off` rule and it should be working. Could I see the eslintrc file or at least part of it to have a look? 

A suggestion would be if you have it the same as below, try restarting the ESLint Server

`eslint config`
```js
module.exports = {
  root: true,
  plugins: ['prefer-smart-quotes'],
  rules: {
    'prefer-smart-quotes/prefer': ['error', 'all'],
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
         'prefer-smart-quotes/prefer': 'off',
      },
    },
  ],
}
```

`ts file` - Doesn't error
```ts
const test = 'Hello my name is "Bob"'
```

`js file` - Does error
```js
const test = 'Hello my name is "Bob"'
```

**Comment by ronny1020** [comment]
I'm very sorry. It works perfectly now. I'm not sure what stupid mistake I had done. Anyway, thanks for your reply.

**Comment by ljbc1994** [comment]
> I'm very sorry. It works perfectly now. I'm not sure what stupid mistake I had done. Anyway, thanks for your reply.

No worries at all!
